version: '3.8'

services:
  web:
    build: .
    restart: always
    volumes:
      - static_volume:/app/LTalk/staticfiles
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=LTalk.settings_docker
    depends_on:
      - db
    networks:
      - ltalk_network

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    restart: always
    networks:
      - ltalk_network

  nginx:
    image: nginx:1.21
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/LTalk/staticfiles
    depends_on:
      - web
    networks:
      - ltalk_network

networks:
  ltalk_network:

volumes:
  postgres_data:
  static_volume: 