# Generated by Django 5.2 on 2025-04-24 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=35)),
                ('translation', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='WordProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_attempts', models.IntegerField(default=0)),
                ('incorrect_attempts', models.IntegerField(default=0)),
                ('is_learned', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.word')),
            ],
        ),
        migrations.CreateModel(
            name='WordSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35)),
                ('description', models.CharField(max_length=200)),
                ('public', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wordsets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='word',
            name='wordsets',
            field=models.ManyToManyField(related_name='words', to='main.wordset'),
        ),
        migrations.CreateModel(
            name='Perfomance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('evaluation_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('wordset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='main.wordset')),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('flashcard', 'Flash Card'), ('fill_blank', 'Fill in the blank'), ('multiple_choice', 'Multiple Choice')], max_length=20)),
                ('question', models.TextField()),
                ('correct_answer', models.TextField()),
                ('wordset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='main.wordset')),
            ],
        ),
    ]
