# Generated by Django 5.2 on 2025-05-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordset',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
