# Generated by Django 5.2 on 2025-05-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_wordset_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseprogress',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='type',
            field=models.CharField(choices=[('flashcard', 'Flash Card'), ('multiple_choice', 'Multiple Choice'), ('fill_in_the_gap', 'Fill in the Gap')], max_length=20),
        ),
    ]
