# Generated by Django 5.2 on 2025-05-02 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_exercise_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentenceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField()),
                ('correct_form', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.word')),
            ],
            options={
                'unique_together': {('word',)},
            },
        ),
    ]
