# Generated by Django 5.2 on 2025-05-03 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_sentencetemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordset',
            name='duplicated_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='main.wordset'),
        ),
    ]
