# Generated by Django 5.2 on 2025-05-03 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_wordset_duplicated_from'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exerciseprogress',
            options={'ordering': ['-answered_at']},
        ),
    ]
