# Generated by Django 5.2 on 2025-05-03 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_exerciseprogress_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exerciseprogress',
            options={'ordering': ['answered_at']},
        ),
    ]
