# Generated by Django 5.2 on 2025-05-05 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_exerciseprogress_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exerciseprogress',
            options={},
        ),
    ]
